# Generated by Django 4.1.2 on 2022-10-26 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_remove_catalogue_type_delete_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalogueWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
