# Generated by Django 4.1.2 on 2022-11-01 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_catalogue_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userComments', to=settings.AUTH_USER_MODEL)),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogueComments', to='auctions.catalogue')),
            ],
        ),
        migrations.AddField(
            model_name='catalogue',
            name='Watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='CatalogueWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
